version: '3.8'

services:
  # Backend API (with SQLite)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: expense-tracker-backend
    environment:
      NODE_ENV: production
      PORT: 5000
      # Use SQLite for simplicity in Docker
      DB_DIALECT: sqlite
      DB_STORAGE: /app/data/database.sqlite
      JWT_SECRET: your-super-secret-jwt-key-here-change-in-production
    ports:
      - "5000:5000"
    networks:
      - expense-tracker-network
    restart: unless-stopped
    volumes:
      - sqlite_data:/app/data

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: expense-tracker-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - expense-tracker-network
    restart: unless-stopped

volumes:
  sqlite_data:

networks:
  expense-tracker-network:
    driver: bridge