version: '3.8'

services:
  # SQL Server Database
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: expense-tracker-db
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ExpenseTracker123!
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - expense-tracker-network
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: expense-tracker-backend
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: database
      DB_PORT: 1433
      DB_NAME: ExpenseTracker
      DB_USER: sa
      DB_PASSWORD: ExpenseTracker123!
      JWT_SECRET: your-super-secret-jwt-key-here-change-in-production
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - expense-tracker-network
    restart: unless-stopped
    volumes:
      - ./backend/src:/app/src:ro
    command: npm run dev

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: expense-tracker-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - expense-tracker-network
    restart: unless-stopped

volumes:
  mssql_data:

networks:
  expense-tracker-network:
    driver: bridge